-- ==========================================================
-- auth-service - esquema base (Postgres).
--
-- Refleja el estado que antes generaba Hibernate con ddl-auto=update.
-- A partir de aca, todo cambio de esquema va en un V2__*.sql, V3__*.sql, etc.
--
-- Sobre bases ya pobladas (volumenes existentes) Flyway hace baseline a
-- esta version y NO ejecuta este script; sobre una base vacia lo corre.
-- ==========================================================

create table credenciales (
    id                bigint       generated by default as identity primary key,
    username          varchar(50)  not null,
    password_hash     varchar(255) not null,
    email             varchar(255),
    intentos_fallidos integer      not null default 0,
    bloqueado_hasta   timestamp(6),
    totp_secret       varchar(64),
    totp_habilitado   boolean      not null default false,
    constraint uk_credenciales_username unique (username)
);

create table refresh_tokens (
    id         bigint       generated by default as identity primary key,
    token      varchar(100) not null,
    username   varchar(50)  not null,
    expira_en  timestamp(6) not null,
    revocado   boolean      not null default false,
    creado_en  timestamp(6) not null,
    constraint uk_refresh_tokens_token unique (token)
);

create index ix_refresh_tokens_username on refresh_tokens (username);
