-- ==========================================================
-- negocio-service - esquema base (Postgres).
--
-- Fusion de los V1__init.sql de catalogo-service y usuarios-service: ahora
-- las 4 tablas viven en la misma base. No hay FK entre juegos.vendedor_username
-- y usuarios.username a proposito: sigue siendo una clave natural (un juego
-- puede quedar "huerfano" si se borra el perfil, y el ABM lo controla a mano).
--
-- A partir de aca, todo cambio de esquema va en un V2__*.sql, etc.
-- ==========================================================

-- ---------- Sub-dominio: usuarios ----------
create table usuarios (
    id              bigint       generated by default as identity primary key,
    username        varchar(50)  not null,
    nombre_completo varchar(255) not null,
    email           varchar(255),
    rol             varchar(20)  not null,
    habilitado      boolean      not null,
    constraint uk_usuarios_username unique (username),
    constraint uk_usuarios_email unique (email)
);

-- ---------- Sub-dominio: catalogo ----------
create table secciones (
    id          bigint      generated by default as identity primary key,
    nombre      varchar(60) not null,
    descripcion varchar(255),
    constraint uk_secciones_nombre unique (nombre)
);

create table juegos (
    id                bigint         generated by default as identity primary key,
    nombre            varchar(120)   not null,
    descripcion       varchar(1000),
    precio            numeric(10, 2) not null,
    stock             integer        not null default 10,
    imagen_url        varchar(255),
    seccion_id        bigint,
    vendedor_username varchar(50)    not null,
    fecha_creacion    timestamp(6)   not null,
    constraint fk_juegos_seccion foreign key (seccion_id) references secciones (id)
);

create index ix_juegos_vendedor on juegos (vendedor_username);
create index ix_juegos_seccion on juegos (seccion_id);

create table compras (
    id                 bigint         generated by default as identity primary key,
    juego_id           bigint         not null,
    nombre_juego       varchar(120)   not null,
    imagen_url         varchar(255),
    precio             numeric(10, 2) not null,
    comprador_username varchar(50)    not null,
    fecha_compra       timestamp(6)   not null,
    constraint uk_compra_juego_comprador unique (juego_id, comprador_username)
);

create index ix_compras_comprador on compras (comprador_username);
